import React from 'react'
import '@mantine/core/styles.css'
import '@mantine/carousel/styles.css'

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core'
import { theme } from '@/theme'
import './Global.css'
import Footer from '@components/Footer/Footer'
import BackToTop from '@components/BackToTop/BackToTop'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          {children}
          <Footer />
          <BackToTop />
        </MantineProvider>
      </body>
    </html>
  )
}
